E_Learning/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('E_Learning_App.urls', namespace='E_Learning_App')),
    path('admin/', admin.site.urls),
]

E_Learning_App/urls.py
from . import views
from django.urls import path

app_name = 'E_Learning_App'

urlpatterns = [

    # URLS basés sur les Templates
    path('', views.sc, name="sc"),
    path('se_connecter', views.sc, name="sc"),
    path('inscrire', views.inscrire, name="inscrire"),
    path('main', views.main, name="main"),
    path('class', views.cls, name="cls"),
    path('about', views.about, name="about"),
    path('contact', views.contact, name="contact"),
    path('remarque', views.remarque, name="remarque"),
    path('profile', views.profile, name="profile"),
    path('cours', views.cours, name="cours"),

    # URLS basés sur les Modèles
    path('signin', views.signin, name="signin"),
    path('signup', views.signup, name="signup"),
    path('remarque/', views.msg, name="msg"),
    path('class/Interactive', views.join_int, name="join_int"),
    path('class/Alphabet', views.join_alp, name="join_alp"),
    path('class/Numbers', views.join_nmb, name="join_nmb"),

]

templates/plat/footer.html
{% load static %}
<div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
    <div class="container py-5">
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <h3 class="text-white mb-4">Get In Touch</h3>
                <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>Bd Laymoune, Casablanca, Maroc</p>
                <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
                <p class="mb-2"><i class="fa fa-envelope me-3"></i>Emsi@Orangers.com</p>
                <div class="d-flex pt-2">
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <h3 class="text-white mb-4">Quick Links</h3>
                <a class="btn btn-link text-white-50" href="{% url 'E_Learning_App:main' %}">Home</a>
                <a class="btn btn-link text-white-50" href="{% url 'E_Learning_App:about' %}">About Us</a>
                <a class="btn btn-link text-white-50" href="{% url 'E_Learning_App:cls' %}">Classes</a>
                <a class="btn btn-link text-white-50" href="{% url 'E_Learning_App:contact' %}">Contact Us</a>
            </div>
            <div class="col-lg-3 col-md-6">
                <h3 class="text-white mb-4">Photo Gallery</h3>
                <div class="row g-2 pt-2">
                    <div class="col-4">
                        <img class="img-fluid rounded bg-light p-1" src="{% static 'img/classes_1.jpg' %}" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid rounded bg-light p-1" src="{% static 'img/classes_2.jpg' %}" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid rounded bg-light p-1" src="{% static 'img/classes_3.jpg' %}" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid rounded bg-light p-1" src="{% static 'img/classes_4.jpg' %}" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid rounded bg-light p-1" src="{% static 'img/classes_5.jpg' %}" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid rounded bg-light p-1" src="{% static 'img/classes_6.jpg' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="copyright">
            <div class="row">
                <div class="col-md-6 text-center text-md-end">
                    <div class="footer-menu">
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/plat/navbar.html
{% load static %}
<head>
    <meta charset="utf-8">
    <title>E-Learning</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="{% static 'img/favicon.ico' %}" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="{% static 'css/pre.css' %}" rel="stylesheet">


    <!-- Icon Font Stylesheet -->
    <link href="{% static 'css/dex.css' %}" rel="stylesheet">
    <link href="{% static 'css/tre.css' %}" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/boostrap.min.css' %}" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="{% static 'css/styyle.css' %}" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-white navbar-light sticky-top px-4 px-lg-5 py-lg-0">
        <a href="{% url 'E_Learning_App:main' %}" class="navbar-brand">
            <h1 class="m-0 text-primary"><i class="fa fa-book-reader me-3"></i>E-Learning</h1>
        </a>
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav mx-auto">

                {% if request.resolver_match.view_name == 'E_Learning_App:main' %}
                <a  href="{% url 'E_Learning_App:main'%}" class="nav-item nav-link active">Home</a>
                {% elif request.resolver_match.view_name == 'E_Learning_App:signin' %}
                <a  href="{% url 'E_Learning_App:main'%}" class="nav-item nav-link active">Home</a>
                {% else %}
                <a  href="{% url 'E_Learning_App:main'%}" class="nav-item nav-link ">Home</a>
                {% endif %}

                {% if request.resolver_match.view_name == 'E_Learning_App:about' %}
                <a href="{% url 'E_Learning_App:about'%}" class="nav-item nav-link active">About Us</a>
                {% else %}
                <a href="{% url 'E_Learning_App:about'%}" class="nav-item nav-link ">About Us</a>
                {% endif %}

                {% if request.resolver_match.view_name == 'E_Learning_App:cls' %}
                <a href="{% url 'E_Learning_App:cls'%}" class="nav-item nav-link active ">Classes</a>
                {% elif request.resolver_match.view_name == 'E_Learning_App:join_int' %}
                <a href="{% url 'E_Learning_App:cls'%}" class="nav-item nav-link active ">Classes</a>
                {% elif request.resolver_match.view_name == 'E_Learning_App:join_alp' %}
                <a href="{% url 'E_Learning_App:cls'%}" class="nav-item nav-link active ">Classes</a>
                {% elif request.resolver_match.view_name == 'E_Learning_App:join_nmb' %}
                <a href="{% url 'E_Learning_App:cls'%}" class="nav-item nav-link active ">Classes</a>
                {% else %}
                <a href="{% url 'E_Learning_App:cls'%}" class="nav-item nav-link  ">Classes</a>
                {% endif %}

                {% if request.resolver_match.view_name == 'E_Learning_App:remarque' %}
                <a href="{% url 'E_Learning_App:remarque'%}" class="nav-item nav-link active">Appointment</a>
                {% else %}
                <a href="{% url 'E_Learning_App:remarque'%}" class="nav-item nav-link ">Appointment</a>
                {% endif %}

                {% if request.resolver_match.view_name == 'E_Learning_App:contact' %}
                <a href="{% url 'E_Learning_App:contact'%}" class="nav-item nav-link active">Contact Us</a>
                {% else %}
                <a href="{% url 'E_Learning_App:contact'%}" class="nav-item nav-link  ">Contact Us</a>
                {% endif %}

            </div>
            <div class="nav-item dropdown btn btn-primary rounded-pill px-3 d-none d-lg-block"  >
                <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" style="color:white"> {{ client.Parent_name }}   </a>
                <div class="dropdown-menu rounded-0 rounded-bottom border-0 shadow-sm m-0 " style="background-color:mintcream">
                    <a href="{% url 'E_Learning_App:profile' %}" class="dropdown-item">Profile</a>
                    <a href="{% url 'E_Learning_App:cours' %}" class="dropdown-item">Cours</a>
                    <a href="{% url 'E_Learning_App:sc' %}" class="dropdown-item">Deconnexion</a>
                </div>
            </div>
        </div>
    </nav>
    <script src="{% static 'js/qua.js' %}"></script>
    <script src="{% static 'js/fiv.js' %}"></script>
    <script src="{% static 'lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>